/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';

import '@stencil/router';
import '@stencil/state-tunnel';
import {
  MatchResults,
} from '@stencil/router';
import {
  ICharacter,
} from './global/apollo-client/marvel-entities';


export namespace Components {

  interface AppCharacter {
    'match': MatchResults;
  }
  interface AppCharacterAttributes extends StencilHTMLAttributes {
    'match'?: MatchResults;
  }

  interface AppHome {}
  interface AppHomeAttributes extends StencilHTMLAttributes {}

  interface AppProfile {
    'match': MatchResults;
  }
  interface AppProfileAttributes extends StencilHTMLAttributes {
    'match'?: MatchResults;
  }

  interface AppRoot {}
  interface AppRootAttributes extends StencilHTMLAttributes {}

  interface CharacterCard {
    'entity': ICharacter;
  }
  interface CharacterCardAttributes extends StencilHTMLAttributes {
    'entity'?: ICharacter;
  }
}

declare global {
  interface StencilElementInterfaces {
    'AppCharacter': Components.AppCharacter;
    'AppHome': Components.AppHome;
    'AppProfile': Components.AppProfile;
    'AppRoot': Components.AppRoot;
    'CharacterCard': Components.CharacterCard;
  }

  interface StencilIntrinsicElements {
    'app-character': Components.AppCharacterAttributes;
    'app-home': Components.AppHomeAttributes;
    'app-profile': Components.AppProfileAttributes;
    'app-root': Components.AppRootAttributes;
    'character-card': Components.CharacterCardAttributes;
  }


  interface HTMLAppCharacterElement extends Components.AppCharacter, HTMLStencilElement {}
  var HTMLAppCharacterElement: {
    prototype: HTMLAppCharacterElement;
    new (): HTMLAppCharacterElement;
  };

  interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {}
  var HTMLAppHomeElement: {
    prototype: HTMLAppHomeElement;
    new (): HTMLAppHomeElement;
  };

  interface HTMLAppProfileElement extends Components.AppProfile, HTMLStencilElement {}
  var HTMLAppProfileElement: {
    prototype: HTMLAppProfileElement;
    new (): HTMLAppProfileElement;
  };

  interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {}
  var HTMLAppRootElement: {
    prototype: HTMLAppRootElement;
    new (): HTMLAppRootElement;
  };

  interface HTMLCharacterCardElement extends Components.CharacterCard, HTMLStencilElement {}
  var HTMLCharacterCardElement: {
    prototype: HTMLCharacterCardElement;
    new (): HTMLCharacterCardElement;
  };

  interface HTMLElementTagNameMap {
    'app-character': HTMLAppCharacterElement
    'app-home': HTMLAppHomeElement
    'app-profile': HTMLAppProfileElement
    'app-root': HTMLAppRootElement
    'character-card': HTMLCharacterCardElement
  }

  interface ElementTagNameMap {
    'app-character': HTMLAppCharacterElement;
    'app-home': HTMLAppHomeElement;
    'app-profile': HTMLAppProfileElement;
    'app-root': HTMLAppRootElement;
    'character-card': HTMLCharacterCardElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
