/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';

import '@stencil/router';
import '@stencil/state-tunnel';
import {
  MatchResults,
} from '@stencil/router';
import {
  ICharacter,
  IComic,
  ICreator,
  IEvent,
  IList,
  ISerie,
  IStory,
} from './global/apollo-client/marvel-entities';


export namespace Components {

  interface AppCharacter {
    'match': MatchResults;
  }
  interface AppCharacterAttributes extends StencilHTMLAttributes {
    'match'?: MatchResults;
  }

  interface AppHome {}
  interface AppHomeAttributes extends StencilHTMLAttributes {}

  interface AppProfile {
    'match': MatchResults;
  }
  interface AppProfileAttributes extends StencilHTMLAttributes {
    'match'?: MatchResults;
  }

  interface AppRoot {}
  interface AppRootAttributes extends StencilHTMLAttributes {}

  interface CharacterCard {
    'entity': ICharacter;
  }
  interface CharacterCardAttributes extends StencilHTMLAttributes {
    'entity'?: ICharacter;
  }

  interface ComicCard {
    'entity': IComic;
  }
  interface ComicCardAttributes extends StencilHTMLAttributes {
    'entity'?: IComic;
  }

  interface CreatorCard {
    'entity': ICreator;
  }
  interface CreatorCardAttributes extends StencilHTMLAttributes {
    'entity'?: ICreator;
  }

  interface EntityList {
    'entitiesList': IList;
  }
  interface EntityListAttributes extends StencilHTMLAttributes {
    'entitiesList'?: IList;
  }

  interface EventCard {
    'entity': IEvent;
  }
  interface EventCardAttributes extends StencilHTMLAttributes {
    'entity'?: IEvent;
  }

  interface SerieCard {
    'entity': ISerie;
  }
  interface SerieCardAttributes extends StencilHTMLAttributes {
    'entity'?: ISerie;
  }

  interface StoryCard {
    'entity': IStory;
  }
  interface StoryCardAttributes extends StencilHTMLAttributes {
    'entity'?: IStory;
  }

  interface NanoPagination {
    'paginationData': IList;
  }
  interface NanoPaginationAttributes extends StencilHTMLAttributes {
    'onPaginationOccured'?: (event: CustomEvent) => void;
    'paginationData'?: IList;
  }
}

declare global {
  interface StencilElementInterfaces {
    'AppCharacter': Components.AppCharacter;
    'AppHome': Components.AppHome;
    'AppProfile': Components.AppProfile;
    'AppRoot': Components.AppRoot;
    'CharacterCard': Components.CharacterCard;
    'ComicCard': Components.ComicCard;
    'CreatorCard': Components.CreatorCard;
    'EntityList': Components.EntityList;
    'EventCard': Components.EventCard;
    'SerieCard': Components.SerieCard;
    'StoryCard': Components.StoryCard;
    'NanoPagination': Components.NanoPagination;
  }

  interface StencilIntrinsicElements {
    'app-character': Components.AppCharacterAttributes;
    'app-home': Components.AppHomeAttributes;
    'app-profile': Components.AppProfileAttributes;
    'app-root': Components.AppRootAttributes;
    'character-card': Components.CharacterCardAttributes;
    'comic-card': Components.ComicCardAttributes;
    'creator-card': Components.CreatorCardAttributes;
    'entity-list': Components.EntityListAttributes;
    'event-card': Components.EventCardAttributes;
    'serie-card': Components.SerieCardAttributes;
    'story-card': Components.StoryCardAttributes;
    'nano-pagination': Components.NanoPaginationAttributes;
  }


  interface HTMLAppCharacterElement extends Components.AppCharacter, HTMLStencilElement {}
  var HTMLAppCharacterElement: {
    prototype: HTMLAppCharacterElement;
    new (): HTMLAppCharacterElement;
  };

  interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {}
  var HTMLAppHomeElement: {
    prototype: HTMLAppHomeElement;
    new (): HTMLAppHomeElement;
  };

  interface HTMLAppProfileElement extends Components.AppProfile, HTMLStencilElement {}
  var HTMLAppProfileElement: {
    prototype: HTMLAppProfileElement;
    new (): HTMLAppProfileElement;
  };

  interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {}
  var HTMLAppRootElement: {
    prototype: HTMLAppRootElement;
    new (): HTMLAppRootElement;
  };

  interface HTMLCharacterCardElement extends Components.CharacterCard, HTMLStencilElement {}
  var HTMLCharacterCardElement: {
    prototype: HTMLCharacterCardElement;
    new (): HTMLCharacterCardElement;
  };

  interface HTMLComicCardElement extends Components.ComicCard, HTMLStencilElement {}
  var HTMLComicCardElement: {
    prototype: HTMLComicCardElement;
    new (): HTMLComicCardElement;
  };

  interface HTMLCreatorCardElement extends Components.CreatorCard, HTMLStencilElement {}
  var HTMLCreatorCardElement: {
    prototype: HTMLCreatorCardElement;
    new (): HTMLCreatorCardElement;
  };

  interface HTMLEntityListElement extends Components.EntityList, HTMLStencilElement {}
  var HTMLEntityListElement: {
    prototype: HTMLEntityListElement;
    new (): HTMLEntityListElement;
  };

  interface HTMLEventCardElement extends Components.EventCard, HTMLStencilElement {}
  var HTMLEventCardElement: {
    prototype: HTMLEventCardElement;
    new (): HTMLEventCardElement;
  };

  interface HTMLSerieCardElement extends Components.SerieCard, HTMLStencilElement {}
  var HTMLSerieCardElement: {
    prototype: HTMLSerieCardElement;
    new (): HTMLSerieCardElement;
  };

  interface HTMLStoryCardElement extends Components.StoryCard, HTMLStencilElement {}
  var HTMLStoryCardElement: {
    prototype: HTMLStoryCardElement;
    new (): HTMLStoryCardElement;
  };

  interface HTMLNanoPaginationElement extends Components.NanoPagination, HTMLStencilElement {}
  var HTMLNanoPaginationElement: {
    prototype: HTMLNanoPaginationElement;
    new (): HTMLNanoPaginationElement;
  };

  interface HTMLElementTagNameMap {
    'app-character': HTMLAppCharacterElement
    'app-home': HTMLAppHomeElement
    'app-profile': HTMLAppProfileElement
    'app-root': HTMLAppRootElement
    'character-card': HTMLCharacterCardElement
    'comic-card': HTMLComicCardElement
    'creator-card': HTMLCreatorCardElement
    'entity-list': HTMLEntityListElement
    'event-card': HTMLEventCardElement
    'serie-card': HTMLSerieCardElement
    'story-card': HTMLStoryCardElement
    'nano-pagination': HTMLNanoPaginationElement
  }

  interface ElementTagNameMap {
    'app-character': HTMLAppCharacterElement;
    'app-home': HTMLAppHomeElement;
    'app-profile': HTMLAppProfileElement;
    'app-root': HTMLAppRootElement;
    'character-card': HTMLCharacterCardElement;
    'comic-card': HTMLComicCardElement;
    'creator-card': HTMLCreatorCardElement;
    'entity-list': HTMLEntityListElement;
    'event-card': HTMLEventCardElement;
    'serie-card': HTMLSerieCardElement;
    'story-card': HTMLStoryCardElement;
    'nano-pagination': HTMLNanoPaginationElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
